### ISSUE TITLE
3.0.0 - 需要更新到能支持短信验证登录的Mirai版本

### ISSUE THREAD

**Issue by UlyssesZh** [rabbitkiller-dev/discord-qq-bridge#45]
已经无法正常使用。

**Comment by rabbitkiller-dev** [comment]
> 已经无法正常使用。

有详细的信息吗

**Comment by UlyssesZh** [comment]
需要更新到能支持短信验证登录的 Mirai, 不然我这里无法登录.

**Comment by WinstonSung** [comment]
Related:
- https://github.com/rabbitkiller-dev/discord-qq-bridge/issues/49

**Comment by WinstonSung** [comment]
(To be confirmed.)

**Comment by WinstonSung** [comment]
Please confirm whether it's fixed or not.

**Comment by rabbitkiller-dev** [comment]
> 需要更新到能支持短信验证登录的 Mirai, 不然我这里无法登录.

可能会比较久, 另一个项目用rust重构尝试. 这个项目基本只维护阶段了, 我目前服务器上的服务目前还能正常跑

**Comment by WinstonSung** [comment]
> ```
> [INFO] Mirai Console Loader Announcement:
> [WARNING] 您目前使用的??源 gitee ?不再受到支持
> [WARNING] 我?已?停止? gitee 源的同步更新
> [WARNING] 如果您依然使用此源, ?不?再受到我?的更新推送
> [WARNING]
> [WARNING] ??
> [WARNING] `- https://mirai.mamoe.net/topic/1084/
> [WARNING] `- https://github.com/project-mirai/mirai-repo-mirror
> [WARNING]
> [WARNING]                 Mamoe Technologies & iTX Technologies
> [WARNING]                                            03/30/2022
> ```

**Comment by WinstonSung** [comment]
- https://mirai.mamoe.net/topic/1084
> ## MCL 无法使用的相关解决方法 - 2022/3/25
>
> [官方公告](https://mirai.mamoe.net/category/1/官方公告) - [Karlatemp](https://mirai.mamoe.net/user/karlatemp) [2022年3月25日 下午11:00](https://mirai.mamoe.net/post/10171)
>
> ----
> 由于 gitee 停止 raw 的直接访问, 我们已经将 mirai-console-loader 的数据文件从 gitee 搬出
> 
> 要继续使用使用 mirai-console-loader, 您需要进行以下的配置
> 
> 1. 打开 `$MCL/config.json`
> 2. 找到
>    `"mirai_repo": "....."`
>    将其地址修改为以下地址中的一个 (注意不要删除双引号 "" (英文半角))
>    * https://repo.mirai.mamoe.net/keep/mcl
>    * https://mirai.mamoe.net/assets/mcl
>    * https://mcl.repo.mamoe.net/
>    * https://repo.itxtech.org/

**Comment by WinstonSung** [comment]
@ferrenlove 

Here.

**Comment by WinstonSung** [comment]
@rabbitkiller-dev 

能帮忙看一下这样是MCL最新版本了吗？
